version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    networks:
      - backend_network
    ports:
      - "5432:5432"
  nest-backend:
    container_name: nest-app
    image: place-hub
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test_db
      - POSTGRES_SCHEMA=public
      - JWT_SECRET=mysecret
      - JWT_EXPIRATION_TIME=1800
      - LOCAL_HOST=3000
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  postgres_data: {}
networks:
  backend_network:
    driver: bridge